- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Amber   #Ferranox Change
  # - Bagel
  # - Box
  # - Elkridge
  # - Fland
  # - Marathon
  # - Oasis
  # - Packed
  # - Plasma
  # - Reach
  # - Exo
  - FerranoxPlanetTest
